#!/usr/bin/env bash
# Configures localhost and facebook.com entries in /etc/hosts.
tmp_file=$(mktemp)

sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > "$tmp_file"
echo "8.8.8.8 facebook.com" >> "$tmp_file"
cat "$tmp_file" > /etc/hosts
rm "$tmp_file"
